# Generated by Django 5.0 on 2024-05-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(upload_to="imgs/"),
        ),
    ]
