# Generated by Django 5.0 on 2025-04-14 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_banner_link_banner_withlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="banner",
            name="priority",
        ),
        migrations.CreateModel(
            name="BannerLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner_languages",
                        to="shop.banner",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.language"
                    ),
                ),
            ],
            options={
                "ordering": ["priority"],
                "unique_together": {("banner", "language")},
            },
        ),
        migrations.AddField(
            model_name="banner",
            name="languages",
            field=models.ManyToManyField(
                through="shop.BannerLanguage", to="shop.language"
            ),
        ),
    ]
